### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by Adholah96** [shafiuyushawu/leaderboard#3]
# **HIGHLIGHTS**✔✔✔

- [ ] Good implementation with fetch and await to consume API.🙌
- [ ] Used KISS and DRY rules in your javascript codes.😊

# **ISSUES**♻♻♻

- [ ] kindly add a little touch and feel to your leadboard design😉

**Comment by shafiuyushawu** [comment]
Thanks @Adholah96 

I will look into it 😄
